export const cards = [
    {
      id: 1,
      title: "Herbal Remedies",
      desc: "Natural Healing",
      img: "https://pmrxcontent.com/wp-content/uploads/herbal-remedies.jpg",
    },
    {
      id: 2,
      title: "Tribal Pottery",
      desc: "Handcrafted Elegance",
      img: "https://img.freepik.com/premium-photo/intricate-traditional-tribal-pottery-natural-light-created-with-generative-ai_419341-54685.jpg?w=360",
    },
    {
      id: 3,
      title: "Harvest Help",
      desc: "Get Farming Hacks",
      img: "https://plus.unsplash.com/premium_photo-1664303389007-20030d003668?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Z3JlZW4lMjBmYXJtfGVufDB8fDB8fHww",
    },
    {
      id: 4,
      title: "Traditional Music Lessons",
      desc: "Folk Melodies",
      img: "https://images.deccanherald.com/deccanherald%2Fimport%2Fsites%2Fdh%2Ffiles%2Fgallery_images%2Ffile752no5t6ix4src945tn.jpg",
    },
    {
      id: 5,
      title: "Beekeeping",
      desc: "BeeHive Help",
      img: "https://boldnewsonline.com/wp-content/uploads/2022/11/beekeeing.jpg",
    },
    {
      id: 6,
      title: "Traditional Art Creation",
      desc: "Art of Ancestors",
      img: "https://rukminim2.flixcart.com/image/850/1000/xif0q/painting/j/n/3/na-14-1-gc14x8t1587-sikhash-original-imagz6qzhy7kujhu.jpeg?q=20&crop=false",
    },
    {
      id: 7,
      title: "Authentic Jewellary",
      desc: "Culture meets Creativity",
      img: "https://indianjeweller.in/public/assets/uploads/news/necklaces.jpg",
    },
    {
      id: 8,
      title: "Hand weaven cloths",
      desc: "Handcrafted Fabrics",
      img: "https://www.soojidaara.in/cdn/shop/articles/handloom.jpg?v=1722429989",
    },
    {
        id: 9,
        title: "Wooden Artifacts",
        desc: "Handcrafted Woodwork",
        img: "https://www.sohrvi.com/cdn/shop/collections/IMG_20221118_144715_446.jpg?v=1682789039",
      },
      {
        id: 10,
        title: "Culinary Services",
        desc: "Flavors of Tradition",
        img: "https://media.licdn.com/dms/image/D5612AQEAvc1BTGHxpA/article-cover_image-shrink_720_1280/0/1703132935692?e=2147483647&v=beta&t=bIqph2a4h3qY0EW8S418qFEMl9Tq6Koxgi7k5dzJcEw",
      },
      {
        id: 11,
        title: "Authentic Pickles",
        desc: "Culture meets Taste",
        img: "https://ffce.in/wp-content/uploads/2018/05/WhatsApp-Image-2024-08-28-at-01.21.23_546bf6cf.jpg",
      },
      {
        id: 12,
        title: "Regional Language services",
        desc: "Traditional Language Guidance",
        img: "https://images.hindustantimes.com/rf/image_size_630x354/HT/p2/2017/08/03/Pictures/_c611e87c-7839-11e7-83e1-68866f5cbeee.jpg",
      },
      
  ];
  
  export const projects = [
    {
      id: 1,
      img: "https://media.istockphoto.com/id/503646746/photo/farmer-spreading-fertilizer-in-the-field-wheat.jpg?s=612x612&w=0&k=20&c=Lgxsjbz0jaYyQrvfzhyAsW2zELtshRP4AtLzkpmcLiE=",
      pp: "https://media.istockphoto.com/id/1125873507/photo/indian-farmer-standing-in-agricultural-field.jpg?s=612x612&w=0&k=20&c=xUOD14TAn0JL2vNE84M8VbEl7Yc_PiFupHO0BoQytNc=",
      cat: "Farming Tips",
      username: "Balraj Singh",
    },
    {
      id: 2,
      img: "https://cdn.shopify.com/s/files/1/0663/6286/8029/collections/know-your-category-600x600-supplementjpg.jpg?v=1677835848",
      pp: "https://www.shutterstock.com/image-photo/portrait-indian-rural-woman-smiling-260nw-2249404243.jpg",
      cat: "Herbal Remedies/Products",
      username: "Rama Devi",
    },
    {
      id: 3,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRo0HGpVUlFnemMNAbWvG_7sADkLenx5Ofjcw&s",
      pp: "https://c8.alamy.com/compfr/ej0tad/portrait-d-une-dame-de-l-inde-rurale-en-sari-vert-ej0tad.jpg",
      cat: "Traditional jewellary(handmade)",
      username: "Nandini Rai",
    },
    {
      id: 4,
      img: "https://img.etimg.com/thumb/msid-92678996,width-640,resizemode-4/news/india/5-fantastic-indian-handicrafts-and-where-to-find-them/indian-traditional-handicrafts.jpg",
      pp: "https://media.istockphoto.com/id/1291626016/photo/indian-farmer.jpg?s=612x612&w=0&k=20&c=yT1HlsdyadgOMfMPDDTkYCpJUdKSHFl-Y463UJN2ISM=",
      cat: "Handicraft products",
      username: "Ramesh Reddy",
    },
    {
      id: 5,
      img: "https://m.media-amazon.com/images/I/91ToK2RkqbL.jpg",
      pp: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRn1Hbaqe90toIJsxxk08Dq73obylpq98AqcA&s",
      cat: "Handmade Book accessories",
      username: "Ajay Mishra",
    },
    {
      id: 6,
      img: "https://5.imimg.com/data5/SELLER/Default/2024/1/381719786/KV/IZ/ZB/210750576/gadwal-pure-handloom-checks-pattu-saree-with-gap-border-red-saree-with-yellow-border-2-500x500.jpeg",
      pp: "https://thumbs.dreamstime.com/b/indian-lady-7221639.jpg",
      cat: "Handloom Saree and dress materials",
      username: "Sushma Rao",
    },
    {
      id: 7,
      img: "https://www.zwende.com/cdn/shop/products/PDP-3_67566c46-1a3a-43b1-bd40-6e599dca9b78.jpg?v=1656058891&width=1080",
      pp: "https://img.freepik.com/premium-photo/potter-work-makes-ceramic-dishes-india-rajasthan_564276-178.jpg",
      cat: "Customised Pottery",
      username: "Hanumanth S",
    },
    {
      id: 8,
      img: "https://www.loomkart.com/cdn/shop/files/fauxsilkcarpetloomkart_neosilk550019_2.jpg?v=1728842435&width=1445",
      pp: "https://t4.ftcdn.net/jpg/05/57/69/27/360_F_557692714_mWe42f6lqGZI36sIWOp2h3D7GQh7TA1X.jpg",
      cat: "Handmade Carpets with traditional designs",
      username: "Shanta Gupta",
    },
  ];
  export const gigs = [
    {
      id: 1,
      img: "https://images.pexels.com/photos/580151/pexels-photo-580151.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create ai art character from your images and prompts",
      price: 59,
      star: 5,
      username: "Anna Bell",
    },
    {
      id: 2,
      img: "https://images.pexels.com/photos/4145190/pexels-photo-4145190.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create ultra high quality character art with ai",
      price: 79,
      star: 5,
      username: "Lannie Coleman",
    },
    {
      id: 3,
      img: "https://images.pexels.com/photos/8797307/pexels-photo-8797307.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1062280/pexels-photo-1062280.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will creating unique ai generated artworks mid journey ai artist",
      price: 112,
      star: 5,
      username: "Carol Steve",
    },
    {
      id: 4,
      img: "https://images.pexels.com/photos/5708069/pexels-photo-5708069.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create custom ai generated artwork using your photos",
      price: 99,
      star: 4,
      username: "Don Weber",
    },
    {
      id: 5,
      img: "https://images.pexels.com/photos/5699456/pexels-photo-5699456.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1771383/pexels-photo-1771383.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will recreate your dreams in high quality pictures",
      price: 59,
      star: 5,
      username: "Audrey Richards",
    },
    {
      id: 6,
      img: "https://images.pexels.com/photos/8100784/pexels-photo-8100784.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/715546/pexels-photo-715546.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create ai digital art illustration hyper realistic painting",
      price: 79,
      star: 4,
      username: "Walton Shepard ",
    },
    {
      id: 7,
      img: "https://images.pexels.com/photos/6039245/pexels-photo-6039245.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/720606/pexels-photo-720606.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will generate images with your prompts using ai dalle",
      price: 89,
      star: 5,
      username: "Waverly Schaefer",
    },
    {
      id: 8,
      img: "https://images.pexels.com/photos/5490778/pexels-photo-5490778.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create custom art using midjourney generator",
      price: 110,
      star: 4,
      username: "Wilton Hunt",
    },
  ];